id: A023A0D1D
base_file: fD94F.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-19 17:59:48.674443
  last_modified_at: 2022-06-19 17:59:48.674446
