id: A023A0D1D
base_file: f544E.txt
type: translation
source_metadata:
  languages:
  - en
  - fr
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-06-19 17:59:48.641306
  last_modified_at: 2022-06-19 17:59:48.641313
