id: A023A0D1D
base_file: f8131.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-06-19 17:59:48.663815
  last_modified_at: 2022-06-19 17:59:48.663821
